site_name: LIBXS
site_author: Hans Pabst
copyright: Copyright (c) Intel Corporation, LIBXS Contributors.
site_description: Library for extra small auxiliary functions and specialized operations.
repo_url: https://github.com/hfp/libxs/
edit_uri: edit/main/documentation
docs_dir: documentation

markdown_extensions:
- toc:
    permalink: True
    toc_depth: 3
    title: None
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.details
- attr_list
- md_in_html
- admonition

extra_css:
- style.css

theme:
    name: readthedocs
    custom_dir: .theme

plugins:
  - search

hooks:
  - .theme/hook.py

nav:
- Overview: index.md
- Ozaki Getting Started:
  - Howto: libxs_ozaki.md
  - Details: samples/libxs_ozaki.md
- LIBXS Domains:
  - Permutation: libxs_perm.md
  - Histogram: libxs_hist.md
  - Registry: libxs_reg.md
  - Hashing: libxs_hash.md
  - Malloc: libxs_malloc.md
  - Memory: libxs_mem.md
  - String: libxs_str.md
  - Timer: libxs_timer.md
  - CPUID: libxs_cpuid.md
  - Utils: libxs_utils.md
  - Sync: libxs_sync.md
  - GEMM: libxs_gemm.md
  - Math: libxs_math.md
  - MHD: libxs_mhd.md
  - RNG: libxs_rng.md
  - Fortran: libxs_fortran.md
- LIBXSTREAM:
  - Reference: libxs_opencl.md
- Example Code:
  - Registry: samples/libxs_registry.md
  - Scratch: samples/libxs_scratch.md
  - Shuffle: samples/libxs_shuffle.md
  - Memory: samples/libxs_memory.md
  - GEMM: samples/libxs_gemm.md
  - Sync: samples/libxs_sync.md
- Tests:
  - Header-Only: tests/headeronly.md
  - Intrinsics: tests/intrinsics.md
  - Histogram: tests/hist.md
  - Registry: tests/registry.md
  - Hashing: tests/hash.md
  - Matdiff: tests/matdiff.md
  - Atomics: tests/atomics.md
  - Malloc: tests/malloc.md
  - Memory: tests/memory.md
  - Timer: tests/timer.md
  - Math: tests/math.md
  - MHD: tests/mhd.md
- Development:
  - Scripts: libxs_scripts.md
- About:
  - License: LICENSE.md
