name: GCC

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  repository_dispatch:
    types: [libxstream-update]

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flags: [DBG=0, DBG=1 PEDANTIC=2 UPLOAD=0]
        libxstream: [lib]
        include:
          - flags: DBG=1 PEDANTIC=2
            libxstream: header-only
    steps:
    - uses: actions/checkout@v5

    - name: Install OpenBLAS
      run: sudo apt install -y libopenblas-openmp-dev

    - name: Install OpenCL
      run: sudo apt install -y opencl-c-headers ocl-icd-libopencl1

    - name: Setup LIBXSTREAM
      run: |
        git clone --depth 1 https://github.com/hfp/libxstream.git ${{ github.workspace }}/../libxstream
        echo "LIBXSTREAMROOT=${{ github.workspace }}/../libxstream" >> ${GITHUB_ENV}

    - name: Build LIBXSTREAM
      if: matrix.libxstream == 'lib'
      run: cd ${LIBXSTREAMROOT} && make -j $(nproc) ${{ matrix.flags }}

    - name: Build LIBXS
      run: make -j $(nproc) ${{ matrix.flags }}

    - name: Test
      run: make -j $(nproc) ${{ matrix.flags }} test

    - name: Build samples
      if: matrix.libxstream == 'header-only'
      run: make -j $(nproc) ${{ matrix.flags }} samples

    - name: Upload
      if: always() && contains(matrix.flags, 'UPLOAD=1')
      run: make clean
    - if: always() && contains(matrix.flags, 'UPLOAD=1')
      uses: actions/upload-artifact@v5
      with:
        name: libxs-dbg
        path: |
          lib/
          tests/*.x
          samples/**/*.x
