name: GCC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flags: [DBG=0, DBG=1 PEDANTIC=2 UPLOAD=1]
    steps:
    - uses: actions/checkout@v4

    - name: Install OpenBLAS
      run: sudo apt install -y libopenblas-openmp-dev

    - name: Install OpenCL
      run: sudo apt install -y opencl-c-headers ocl-icd-libopencl1

    - name: Setup LIBXSTREAM
      run: |
        git clone --depth 1 https://github.com/hfp/libxstream.git ${{ github.workspace }}/../libxstream
        echo "LIBXSTREAMROOT=${{ github.workspace }}/../libxstream" >> ${GITHUB_ENV}

    - name: Build LIBXSTREAM
      run: cd ${LIBXSTREAMROOT} && make -j $(nproc) ${{ matrix.flags }}

    - name: Build LIBXS
      run: make -j $(nproc) ${{ matrix.flags }}

    - name: Test
      run: make -j $(nproc) ${{ matrix.flags }} test

    - name: Upload
      if: always() && contains(matrix.flags, 'UPLOAD=1')
      run: make clean
    - if: always() && contains(matrix.flags, 'UPLOAD=1')
      uses: actions/upload-artifact@v4
      with:
        name: libxs-dbg
        path: |
          lib/
          tests/*.x
          samples/**/*.x
